version: '3'

services:
  grav:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${GRAV_IMAGE}:${GRAV_TAG}
    restart: unless-stopped
    volumes:
      - users:/var/www/grav/user
      - logs:/var/www/grav/log
      - backups:/var/www/grav/backup
    environment:
      DUID: 1000
      DGID: 1000
      DOMAIN: ${DOMAIN}
      VIRTUAL_HOST: ${DOMAIN},www.${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN},www.${DOMAIN}

volumes:
  users:
  backups:
  logs:

networks:
  default:
    name: ${NETWORK}
    external: true
