version: '3'

services:
  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb
    image: ${MARIADB_IMAGE}:${MARIADB_TAG}
    stop_grace_period: 3m
    restart: always
    volumes:
      - backup:/backup
      - mariadb:/var/lib/mysql
      - mariadb-logs:/logs
    environment:
      TIMEZONE: ${TIMEZONE}
      CONTAINER_NAME: ${COMPOSE_PROJECT_NAME}-mariadb
      ROOT_PASS: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: nextcloud
      DB_USER: nextcloud
      DB_PASS: ${MYSQL_PASSWORD}
      DB_BACKUP: TRUE
      DB_BACKUP_NAME: nextcloud
      DB_BACKUP_USER: nextcloud
      DB_BACKUP_PASS: ${MYSQL_PASSWORD}

  nextcloud:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${NEXTCLOUD_IMAGE}:${NEXTCLOUD_TAG}
    hostname: ${DOMAIN}
    restart: always
    depends_on:
      - mariadb
    volumes:
      - data:/data/userdata
      - config:/www/nextcloud/config
      - apps:/data/apps
      - themes:/www/nextcloud/themes
      - nextcloud-logs:/www/logs
      - templates:/data/templates
    environment:
      CRON_PERIOD: 5
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASS: ${ADMIN_PASS}
      DOMAIN: ${DOMAIN}
      DB_TYPE: mysql
      DB_HOST: ${COMPOSE_PROJECT_NAME}-mariadb
      NEXTCLOUD_UPDATE: 1
      DB_NAME: nextcloud
      DB_USER: nextcloud
      DB_PASS: ${MYSQL_PASSWORD}
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
    cap_add:
      - NET_ADMIN

volumes:
  backup:
  mariadb:
  mariadb-logs:
  data:
  config:
  apps:
  themes:
  nextcloud-logs:
  templates:

networks:
  default:
    name: ${NETWORK}
    external: true