services:
  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    image: ${POSTGRES_IMAGE}:${POSTGRES_TAG}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      SUPERUSER_USER: ${SUPERUSER_USER}
      SUPERUSER_PASS: ${SUPERUSER_PASS}
      DB_EXTENSION: ${DB_EXTENSION}
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  default:
    name: ${NETWORK}
    external: true
