version: '3'

services:
  android:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${ANDROID_IMAGE}:${ANDROID_TAG}
    restart: always
    devices:
      - /dev/kvm
    environment:
      EMULATOR_DEVICE: ${EMULATOR_DEVICE}
      WEB_VNC: true
    volumes:
      - data:/home/androidusr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.android.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.android.loadbalancer.server.port=6080"
      - "traefik.http.routers.android.entrypoints=websecure"
      - "traefik.http.routers.android.tls.certresolver=myresolver"
      
volumes:
  data:

networks:
  default:
    name: ${NETWORK}
    external: true
