services:
  android:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${ANDROID_IMAGE}:${ANDROID_TAG}
    restart: always
    devices:
      - /dev/kvm
    environment:
      EMULATOR_DEVICE: ${EMULATOR_DEVICE}
      WEB_VNC: true
    volumes:
      - data:/home/androidusr
    environment:
      VIRTUAL_PORT: 6080
      VIRTUAL_HOST: ${DOMAIN},www.${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN},www.${DOMAIN}
      
volumes:
  data:

networks:
  default:
    name: ${NETWORK}
    external: true
