version: '3'

services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb
    image: ${MARIADB_IMAGE}:${MARIADB_TAG}
    volumes:
      - speedtest-db:/var/lib/mysql
    restart: always
    environment:
      - MARIADB_DATABASE: ${MARIADB_DATABASE}
      - MARIADB_USER: ${MARIADB_USER}
      - MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      - MARIADB_RANDOM_ROOT_PASSWORD: true

  speedtest-tracker:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${SPEED_TEST_TRACKER_IMAGE}:${SPEED_TEST_TRACKER_TAG}
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - PUID: ${PUID}
      - PGID: ${PGID}
      - APP_NAME: ${APP_NAME}
      - APP_KEY: ${APP_KEY}
      - DB_CONNECTION: mysql
      - DB_HOST: ${COMPOSE_PROJECT_NAME}-mariadb
      - DB_PORT: 3306
      - DB_DATABASE: ${MARIADB_DATABASE}
      - DB_USERNAME: ${MARIADB_USER}
      - DB_PASSWORD: ${MARIADB_PASSWORD}
      - SPEEDTEST_SCHEDULE: ${SPEEDTEST_SCHEDULE}
      - SPEEDTEST_SERVERS: ${SPEEDTEST_SERVERS}
      - PRUNE_RESULTS_OLDER_THAN: ${PRUNE_RESULTS_OLDER_THAN}
      - CHART_DATETIME_FORMAT: ${CHART_DATETIME_FORMAT}
      - DATETIME_FORMAT: ${DATETIME_FORMAT}
      - APP_TIMEZONE: ${APP_TIMEZONE}
      - TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      - VIRTUAL_HOST: ${URL_DOMAIN}
      - LETSENCRYPT_HOST: ${URL_DOMAIN}
    volumes:
      - speedtest-tracker-config:/config
      
volumes:
  speedtest-db:
  insight:

networks:
  default:
    name: ${NETWORK}
    external: true
