version: '3'

services:
  mongodb:
    container_name: ${COMPOSE_PROJECT_NAME}-mongo
    image: mongo:${MONGO_TAG}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - mongo-logs:/var/log/mongodb
    healthcheck:
      test: mongosh --eval 'db.runCommand({serverStatus:1}).ok' --quiet | grep 1
      interval: 5s
      timeout: 3s
      retries: 10

  elasticsearch:
    container_name: ${COMPOSE_PROJECT_NAME}-elasticsearch
    image: elasticsearch:${ELASTICSEARCH_TAG}
    restart: always
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=${DISCOVERY_TYPE}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536
    mem_limit: ${MEMORY_LIMIT}
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s" ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  mongo-data:
  mongo-logs:
  elasticsearch-data:

networks:
  default:
    name: ${NETWORK}
    external: true
