version: '3'

services:
  mongodb:
    container_name: ${COMPOSE_PROJECT_NAME}-mongo
    image: mongo:${MONGO_TAG}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - mongo-logs:/var/log/mongodb
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  elasticsearch:
    container_name: ${COMPOSE_PROJECT_NAME}-elasticsearch
    image: elasticsearch:${ELASTICSEARCH_TAG}
    restart: always
    environment:
      - cluster.name=elasticsearch
      - discovery.type=${DISCOVERY_TYPE}
      - xpack.security.enabled=false
      - http.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536
    mem_limit: ${MEMORY_LIMIT}
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl -fsSL http://localhost:9200/_cat/health?h=status | grep -q -E 'green|yellow'"
      ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 1m

volumes:
  mongo-data:
  mongo-logs:
  elasticsearch-data:

networks:
  default:
    name: ${NETWORK}
    external: true
