version: '3'
services:
  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb
    image: ${MARIADB_IMAGE}:${MARIADB_TAG}
    restart: always
    volumes:
       - phorge_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --innodb-buffer-pool-size=268435456 --local-infile=0 --max-allowed-packet=33554432 --sql-mode=STRICT_ALL_TABLES

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    image: nginx:alpine
    volumes:
      - phorge_web:/var/www/html
     # - ./config/phorge_nginx.conf:/etc/nginx/templates/nginx.conf.template
      # UNCOMMENT IF USING NGINX FOR SSL TERMINATION
      # - ./config/yourdomain.test.crt:/etc/nginx/certs/yourdomain.test.crt
      # - ./config/yourdomain.test.key:/etc/nginx/certs/yourdomain.test.key
    # ports:
      # CHANGE TO "80:80" IF USING NGINX FOR SSL TERMINATION
      # - 9080:80
      # UNCOMMENT IF USING NGINX FOR SSL TERMINATION
      # - 443:443
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      # https://nginx.org/en/docs/ngx_core_module.html#worker_processes
      NGINX_WORKER_PROCESSES: auto
      # https://nginx.org/en/docs/ngx_core_module.html#worker_rlimit_nofile
      NGINX_WORKER_RLIMIT_NOFILE: 65535
      # https://nginx.org/en/docs/ngx_core_module.html#worker_connections
      NGINX_WORKER_CONNECTIONS: 65535
      # https://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_timeout
      NGINX_KEEPALIVE_TIMEOUT: 60s
      # https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
      NGINX_CLIENT_MAX_BODY_SIZE: 200m
      # https://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_timeout
      NGINX_CLIENT_BODY_TIMEOUT: 90s
      # https://nginx.org/en/docs/http/server_names.html
      NGINX_HOST: ${PH_BASE_URI}
      # UNCOMMENT IF USING NGINX FOR SSL TERMINATION
      # - NGINX_SSL_CERT=yourdomain.test.crt
      # - NGINX_SSL_KEY=yourdomain.test.key
      # VIRTUAL_PORT: 9080
      VIRTUAL_HOST: ${PH_BASE_URI}, www.${PH_BASE_URI}
      LETSENCRYPT_HOST: ${PH_BASE_URI}, www.${PH_BASE_URI}

  phorge:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${PHORGE_IMAGE}:${PHORGE_TAG}
    restart: always
    volumes:
      - phorge_web:/var/www/html
      - phorge_ssh:/etc/ssh
      - phorge_repo:/var/repo
     # - ./config/phorge_mailers.json:/usr/src/docker_ph/mailers.json
    depends_on:
      - mariadb
      - nginx
    environment:
      UPGRADE_ON_RESTART: true
      PH_MYSQL_PASS: ${MYSQL_ROOT_PASSWORD}
     # PH_CLUSTER_MAILERS: true
      PH_BASE_URI: https://${PH_BASE_URI}
    ports:
      # SSH Port
      - 2530:2530

volumes:
  phorge_db:
  phorge_web:
  phorge_ssh:
  phorge_repo:

networks:
  default:
    name: ${NETWORK}
    external: true
