version: '3'

services:
  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb
    image: ${MARIADB_IMAGE}:${MARIADB_TAG}
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      TIMEZONE: ${TIMEZONE}
      ROOT_PASS: ${ROOT_PASS}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

  teampass:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${TEAMPASS_IMAGE}:${TEAMPASS_TAG}
    restart: unless-stopped
    depends_on:
      - mariadb
    links:
      - mariadb:mariadb
    volumes:
      - data:/www/
      - logs:/www/logs
    environment:
      DB_HOST: ${COMPOSE_PROJECT_NAME}-mariadb
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      VIRTUAL_HOST: ${DOMAIN},www.${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN},www.${DOMAIN}

volumes:
  mariadb:
  data:
  logs:

networks:
  default:
    name: ${NETWORK}
    external: true
