version: '3'

services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    image: ${MYSQL_IMAGE}:${MYSQL_TAG}
    restart: unless-stopped
    hostname: ${DB_HOSTNAME}
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  dbdata:
  
networks:
  default:
    name: ${NETWORK}
    external: true
