version: '3'

services:
  gitlab-ee:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    hostname: ${GITLAB_HOSTNAME}
    image: ${GITLAB_EE_IMAGE}:${GITLAB_EE_TAG}
    restart: always
    environment:
      TZ: ${TZ}
      GITLAB_TIMEZONE: ${TZ}
      VIRTUAL_NETWORK: ${NETWORK}
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: ${GITLAB_HOST}
      LETSENCRYPT_HOST: ${GITLAB_HOST}
      CONTAINER_NAME: ${COMPOSE_PROJECT_NAME}-app
      DEBUG: false
      DB_ADAPTER: postgresql
      DB_HOST: ${COMPOSE_PROJECT_NAME}-postgres
      DB_PORT: 5432
      DB_USER: gitlab
      DB_PASS: password
      DB_NAME: gitlab
      REDIS_HOST: ${COMPOSE_PROJECT_NAME}-redis
      REDIS_PORT: 6379
      USERMAP_UID: 60000
      USERMAP_GID: 60000
      GITLAB_HTTPS: true
      SSL_SELF_SIGNED: false
      GITLAB_HOST: ${GITLAB_HOSTNAME}
      GITLAB_PORT: 443
      GITLAB_SSH_PORT: 10022
      GITLAB_ROOT_PASSWORD: password
      GITLAB_REGISTRY_ENABLED: false
    depends_on:
      - redis
      - postgres
    volumes:
      - data:/home/git/data:Z
      - gitlab-logs:/var/log/gitlab
      - nginx-logs:/www/logs/nginx

  redis:
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    image: ${REDIS_IMAGE}:${REDIS_TAG}
    volumes:
      - redis:/var/lib/redis
    environment:
      CONTAINER_NAME: ${COMPOSE_PROJECT_NAME}-redis
      ZABBIX_SERVER: zabbix-server
      ZABBIX_SERVER_PORT: 10051
    restart: always

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    image: ${POSTGRES_IMAGE}:${POSTGRES_TAG}
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gitlab
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: password
      CONTAINER_NAME: ${COMPOSE_PROJECT_NAME}-postgres
    restart: always

volumes:
  data:
  gitlab-logs:
  nginx-logs:
  redis:
  postgres:

networks:
  default:
    name: ${NETWORK}
    external: true
