version: '3'

services:
  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb
    image: ${MARIADB_IMAGE}:${MARIADB_TAG}
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      TIMEZONE: ${TIMEZONE}
      ROOT_PASS: ${ROOT_PASS}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

  libreplan:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${LIBREPLAN_IMAGE}:${LIBREPLAN_TAG}
    restart: unless-stopped
    links:
      - mariadb
    volumes:
      - data:/www/wordpress
      - logs:/www/logs
    environment:
      LIBREPLAN_DBHOST: ${COMPOSE_PROJECT_NAME}-mariadb
      LIBREPLAN_DBPORT: 3306
      LIBREPLAN_DBNAME: ${DB_NAME}
      LIBREPLAN_DBUSER: ${DB_USER}
      LIBREPLAN_DBPASSWORD: ${DB_PASS}
      VIRTUAL_HOST: ${SITE_URL},www.${SITE_URL}
      LETSENCRYPT_HOST: ${SITE_URL},www.${SITE_URL}

volumes:
  mariadb:
  data:
  logs:

networks:
  default:
    name: ${NETWORK}
    external: true
