version: '3'
services:
  openldap:
    hostname: ${OPENLDAP_HOSTNAME}
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${LDAP_IMAGE}:${LDAP_TAG}
    restart: always
    environment:
      LDAP_FORCE_STARTTLS: "true"
      LDAP_DOMAIN: "customdomain.com"
      LDAP_BASEDN: "dc=customdomain,dc=com"
      LDAP_ORGANISATION: "Custom Domain, Inc."
      LDAP_BINDDN: "cn=admin,dc=customdomain,dc=com"
    ports:
      - ${LDAP_PORT}:389
      - ${LDAPS_PORT}:636
    volumes:
      - data:/var/lib/openldap

  phpldapadmin:
    container_name: ${COMPOSE_PROJECT_NAME}-phpldapadmin
    image: ${PHPLDAPADMIN_IMAGE}:${PHPLDAPADMIN_TAG}
    restart: always
    depends_on:
      - openldap
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ${OPENLDAP_HOSTNAME}
      PHPLDAPADMIN_HTTPS: false
      VIRTUAL_HOST: ${PHPLDAPADMIN_HOSTNAME}
      LETSENCRYPT_HOST: ${PHPLDAPADMIN_HOSTNAME}

volumes:
  data:

networks:
  default:
    name: ${NETWORK}
    external: true
