version: '3'
services:
  openldap:
    hostname: ${OPENLDAP_HOSTNAME}
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${LDAP_IMAGE}:${LDAP_TAG}
    restart: always
    environment:
      LDAP_FORCE_STARTTLS: ${LDAP_FORCE_STARTTLS}
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_BASEDN: ${LDAP_BASEDN}
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_BINDDN: ${LDAP_BINDDN}
      LDAP_SECRET: ${LDAP_SECRET}
    ports:
      - ${LDAP_PORT}:389
      - ${LDAPS_PORT}:636
    volumes:
      - data:/var/lib/openldap

  phpldapadmin:
    container_name: ${COMPOSE_PROJECT_NAME}-phpldapadmin
    image: ${PHPLDAPADMIN_IMAGE}:${PHPLDAPADMIN_TAG}
    restart: always
    depends_on:
      - openldap
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ${OPENLDAP_HOSTNAME}
      PHPLDAPADMIN_HTTPS: false
      VIRTUAL_HOST: ${PHPLDAPADMIN_HOSTNAME}
      LETSENCRYPT_HOST: ${PHPLDAPADMIN_HOSTNAME}

volumes:
  data:

networks:
  default:
    name: ${NETWORK}
    external: true
