version: '3'

services:
  unbound:
    container_name: ${COMPOSE_PROJECT_NAME}-unbound
    image: mvance/unbound:${UNBOUND_TAG}
    restart: unless-stopped
    hostname: unbound
    volumes:
      - unbound-data:/opt/unbound/etc/unbound/
    cap_add:
      - NET_ADMIN
    networks:
      private_network:
        ipv4_address: ${UNBOUND_IP}
      default:

  pihole:
    container_name: ${COMPOSE_PROJECT_NAME}-pihole
    image: pihole/pihole:${PIHOLE_TAG}
    restart: unless-stopped
    hostname: pihole
    depends_on:
      - unbound
    dns:
      - 127.0.0.1
      - ${UNBOUND_IP}
    volumes:
      - pihole-data:/etc/pihole/
      - dnsmasq:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    environment:
      TZ: ${TIMEZONE}
      WEBPASSWORD: ${WEBPASSWORD}
      VIRTUAL_HOST: ${URL_DOMAIN}
      LETSENCRYPT_HOST: ${URL_DOMAIN}
    networks:
      private_network:
        ipv4_address: ${PIHOLE_IP}
      default:

volumes:
  unbound-data:
  pihole-data:
  dnsmasq:

networks:
  default:
    name: ${NETWORK}
    external: true
  private_network:
    name: ${PRIVATE_NETWORK}
    ipam:
      driver: default
      config:
        - subnet: ${PRIVATE_NETWORK_SUBNET}