version: "3.8"

services:
  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    hostname: ${COMPOSE_PROJECT_NAME}-postgres
    image: ${POSTGRES_IMAGE}:${POSTGRES_TAG}
    environment:
      TIMEZONE: ${TIMEZONE}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SUPERUSER_PASS: ${SUPERUSER_PASS}
      DB_EXTENSION: ${DB_EXTENSION}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
      
  gnuhealth-admin:
    container_name: ${COMPOSE_PROJECT_NAME}-admin
    hostname: ${COMPOSE_PROJECT_NAME}-admin
    image: ${GNUHEALTH_IMAGE}:${GNUHEALTH_TAG}
    environment:
      TZ: ${TIMEZONE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS} 
    command:
      - /bin/bash
      - -c
      - |
        (until echo > /dev/tcp/${COMPOSE_PROJECT_NAME}-postgres/5432; do sleep 0.5; done) 2>/dev/null
        echo "${PASSWORD:-admin}" > /tmp/.passwd
        TRYTONPASSFILE=/tmp/.passwd /entrypoint.sh trytond-admin -d "${DB_NAME:-tryton}" --all -l ${GNUHEALTH_LANGUAGE} --email "${EMAIL:-}" -vv
        if command -v uwsgi &>/dev/null; then uwsgi --ini /etc/uwsgi.conf; else gunicorn --config=/etc/gunicorn.conf.py; fi
    depends_on:
      - postgres
    restart: "no"

  gnuhealth-app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    hostname: ${COMPOSE_PROJECT_NAME}-app
    image: ${GNUHEALTH_IMAGE}:${GNUHEALTH_TAG}
    environment:
      TZ: ${TIMEZONE}
      VIRTUAL_PORT: 8000
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS} 
      VIRTUAL_HOST: ${URL},www.${URL}
      LETSENCRYPT_HOST: ${URL},www.${URL}
    volumes:
      - gnuhealth-data:/var/lib/trytond/db
    command:
      - /bin/bash
      - -c
      - |
        (until echo > /dev/tcp/${COMPOSE_PROJECT_NAME}-postgres/5432; do sleep 0.5; done) 2>/dev/null
        echo "${PASSWORD:-admin}" > /tmp/.passwd
        TRYTONPASSFILE=/tmp/.passwd /entrypoint.sh trytond -d "${DB_NAME:-tryton}" -vv
        if command -v uwsgi &>/dev/null; then uwsgi --ini /etc/uwsgi.conf; else gunicorn --config=/etc/gunicorn.conf.py; fi
    depends_on:
      - postgres
    restart: always

  gnuhealth-cron:
    container_name: ${COMPOSE_PROJECT_NAME}-cron
    image: ${GNUHEALTH_IMAGE}:${GNUHEALTH_TAG}
    environment:
      DB_PASSWORD: ${DB_PASS} 
    volumes:
      - gnuhealth-data:/var/lib/trytond/db
    command:
      - /bin/bash
      - -c
      - |
        (until echo > /dev/tcp/${COMPOSE_PROJECT_NAME}-app/8000; do sleep 0.5; done) 2>/dev/null
        trytond-cron -d "${DB_NAME}"
    depends_on:
      - postgres
      - gnuhealth-app
    restart: always

  mailhog:
    container_name: ${COMPOSE_PROJECT_NAME}-mailhog
    image: ${MAILHOG_IMAGE}:${MAILHOG_TAG}
    restart: always
    ports:
      - ${MAILHOG_SMTP_PORT}:1025
      - ${MAILHOG_HTTP_PORT}:8025

volumes:
  postgres-data:
  gnuhealth-data:

networks:
  default:
    name: ${NETWORK}
    external: true
