version: '3'

services:
  gitlab-ce-runner:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: gitlab/gitlab-runner:${GITLAB_CE_RUNNER_TAG}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - config:/etc/gitlab-runner/
      - cache:/cache
    environment:
      TZ: ${TZ}

    volumes:
      - config:/etc/gitlab-runner/
      
volumes:
  config:
  cache:

networks:
  default:
    name: ${NETWORK}
    external: true
