version: '3'

services:
  gitlab-ce-runner:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: gitlab/gitlab-runner:${GITLAB_CE_RUNNER_TAG}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - config:/etc/gitlab-runner/
      - cache:/cache
    environment:
      TZ: ${TZ}
      
  gitlab-ce-runner-register:
    container_name: ${COMPOSE_PROJECT_NAME}-register
    restart: 'no'
    image: gitlab/gitlab-runner:${GITLAB_CE_RUNNER_TAG}
    depends_on:
      - gitlab-ce-runner
    environment:
      CI_SERVER_URL: ${CI_SERVER_URL}
      REGISTRATION_TOKEN: ${REGISTRATION_TOKEN}
    command:
      - register
      - --non-interactive
      - --url=${CI_SERVER_URL}
      - --token ${REGISTRATION_TOKEN}
      - --executor=docker
      - --docker-image=docker:latest
      - --description=${RUNNER_NAME}
      - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
    volumes:
      - config:/etc/gitlab-runner/
      - cache:/cache
      
volumes:
  config:
  cache:

networks:
  default:
    name: ${NETWORK}
    external: true
